### ISSUE TITLE
Buildings and Ressources that are not in buildings.rst

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/docs#7]
That Buildings and Resources needs to be added:

Buildings:
PIGSTY           = 39
CANNON_FOUNDRY   = 67
STONE_DEPOSIT    = 70
BARRIER	         = 71

Ressources:
SWORDSMAN        = 1000023
GOLD             =  1
PIGS             = 34
ACORNS           = 39
STONE_DEPOSIT    = 51
CANDLES

**Comment by ChrisOelmueller** [comment]
@LinuxDonald 

These files are generated, so you should be able to simply execute `buildings.py` according to the docs and receive an updated `buildings.rst`

**Comment by LinuxDonald** [comment]
```
[linuxdonald@linuxdonald-pc docs-uh]$ python2 buildings.py
Error: Unsupported Python version                                                                                                                                                                                                                                              
Python3.4 or higher is required to run Unknown Horizons.                                                                                                                                                                                                                       
[linuxdonald@linuxdonald-pc docs-uh]$ python buildings.py                                                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                                                                             
  File "buildings.py", line 8, in <module>                                                                                                                                                                                                                                     
    from init import db                                                                                                                                                                                                                                                        
  File "/home/linuxdonald/dev/docs-uh/init.py", line 19, in <module>                                                                                                                                                                                                           
    init_environment(True)                                                                                                                                                                                                                                                     
  File "./run_uh.py", line 353, in init_environment                                                                                                                                                                                                                            
    setup_fife()                                                                                                                                                                                                                                                               
  File "./run_uh.py", line 343, in setup_fife                                                                                                                                                                                                                                  
    if (fife_version_major, fife_version_minor, fife_version_patch) < VERSION.REQUIRED_FIFE_VERSION:                                                                                                                                                                           
TypeError: '<' not supported between instances of 'Dummy' and 'int'                                                                                                                                                                                                            
[linuxdonald@linuxdonald-pc docs-uh]$ 

```

**Comment by AndyMender** [comment]
@LinuxDonald , I did some 2to3 refactoring and cleaning in this repository. Sorry for the delay, but major changes were required.

**Comment by LinuxDonald** [comment]
@AndyMender good work :) updated with: https://github.com/unknown-horizons/docs/commit/b1dbfd397bdf653f5fb5079d80d262a7921c67a0
